### ISSUE TITLE
Upgrade planned to support Extension API Version v2.0.0?

### ISSUE THREAD

**Issue by ecogit** [nicolasm/ulauncher-pinboard-search#2]
Thank you Nicolas for having had created this extension! Surely it is used by quite a few Linux users who are also infoholics.  

Since the new Extension API Version v2.0.0 is out (coinciding with upgrade to ULauncher v5), your handy extension is not working anymore and consequently also ceased to be listed at [Discover Extensions](https://ext.ulauncher.io/?api_version=2.0.0). 

Do you have plans to develop an upgrade?

**Comment by nicolasm** [comment]
Hi Hans,
Yes, I am going to upgrade it!

In fact lately I have been using Rofi instead of Ulauncher so it is only recently that I have discovered Ulauncher had migrated to Python 3 and that the extensions needed to be migrated.

**Comment by nicolasm** [comment]
It's been migrated and working fine!

**Comment by ecogit** [comment]
Thank you Nicolas for prompt action 🍻

I just tested on my side as well, works flawlessly.
